### ISSUE TITLE
Swift version by Mapbox

### ISSUE THREAD

**Issue by incanus** [tingslabs/TIMapboxGeocoder#1]
Hey @BenjaminDigeon, nice work here. Were you aware of https://github.com/mapbox/MapboxGeocoder.swift?

**Comment by BenjaminDigeon** [comment]
Yes I am fully aware of the existence of a Swift version, but I wanted to keep the majority of my code in objective-c and use Cocoapods. So I converted the swift code in objective-c with some changes :smile:

**Comment by incanus** [comment]
Ok, just checking! Mind at least linking to the Swift project, since you based on it?

**Comment by l0ck3** [comment]
@incanus I credited your Swift implementation in the Readme. 

Is that fine for you?
